# Sanwa gamepad (JY-P70UR)
axis_roll_ : 3
axis_pitch_ : 2
axis_thrust_ : 1
# buttons for iris yaw :( so use left and right bumpers
button_yaw_left_: 6
button_yaw_right_: 8
# make it more fun to fly
max_roll: 0.3
max_pitch: 0.3
max_yaw_rate: 3
