robots:
  - robot1
  - robot2

robot1:
  x: 0.0
  y: -2.0
  z: 0.31
  Y: -1.570796
  map_only: false
  map_filename: ''
  output: log # screen, log, null

robot2:
  x: 0.0
  y: 0.0
  z: 0.31
  Y: 0
  map_only: false
  map_filename: ''
  output: log

robot3:
  x: -16
  y: -2
  Y: 0

robot4:
  x: -16
  y: 2
  Y: -3.14159265

robot5:
  x: -8
  y: 2
  Y: 3.14159265

robot6:
  x: 0
  y: 2
  Y: 3.14159265

robot7:
  x: 8
  y: 2
  Y: 3.14159265

robot8:
  x: 16
  y: 2
  Y: 3.14159265

robot9:
  x: 16
  y: -2
  Y: 0

robot10:
  x: 8
  y: -2
  Y: 0
